language: java
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - COVERALLS_REPO_TOKEN=R2bf8wWXuB66P1sDcsFWqQGBv4VqldWeV

notifications:
  email:
    recipients:
    - witmic1@gmail.com
    - stegschreck@gmail.com
    on_success: change
    on_failure: always

after_success:
- ./gradlew cobertura coveralls
